apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: serverless
resources:
  - fn1.yaml
  - fn2.yaml
#  - git-secret.yaml
  - git_repo.yaml
secretGenerator:
  - name: git-credentials
    env: git-repo-credentials.env
#    envs:
#      - git-repo-credentials.env
